### ISSUE TITLE
How does this compare to GraphQL

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-restapi#13]
Having just decided to move forward with this repository and moved it into aiidateam, I'm now going to be fickle and ask "why are we using REST instead of GraphQL?"

From the (naturally biased) opinion of graphql site, this is why it is better than REST: https://www.howtographql.com/basics/1-graphql-is-the-better-rest/

Particularly the new `/querybuilder` endpoint feels like essentially a bespoke implementation of graphql, but lacking things like pagination, typing etc.

Note there has already been a trial version of this in https://github.com/dev-zero/aiida-graphql, using https://pypi.org/project/strawberry-graphql. At the time a drawback was that in only supported python 3.7+, but this is no longer an issue since aiida-core only supports this.

This is certainly not to say I am insisting we do move to graphql, but I think it's good to have some "due diligence" here to say we have considered it.

Here's some youtube vids (the best source of research 😆) with a more balanced look:

- https://www.youtube.com/watch?v=S1wQ0WvJK64 (Why I Don’t Use GraphQL Anymore)
- https://www.youtube.com/watch?v=AYZOHt6kz6Y (GraphQL vs REST for Side Projects)

Essentially I think it comes down to: GraphQL can be more complex to implement on the backend, but can be more powerful on the frontend (for clients). 
So, do we except the outcome being a less powerful API, but with the benefit of (probably) easier development/maintenance? (quite possibly)

**Comment by chrisjsewell** [comment]
Thoughts @ltalirz, @NinadBhat?

**Comment by ltalirz** [comment]
I have considered it. Here are my thoughts:

 1. The main purpose of our update here is to extend the REST API towards creation of entities for workflow management. While GraphQL can also be used to mutate data on the server, I expect that much of the potential benefit would come in the domain of querying. We would have to pay a very high price (rewrite all apps relying on the current rest api + replicate all functionality in graphql) for a questionable reward (unclear whether it's really easier to use for creating new entities, at least to me).
 
 2. The `aiida-graphql` plugin is a nice demo and GraphQL may indeed be a suitable query language to adopt in AiiDA but so far the plugin just adds another layer (GraphQL) on top of the QueryBuilder. 
    In order to truly take advantage of GraphQL we would need to replace the QueryBuilder with it entirely. Until that happens, the `/querybuilder` endpoint makes a lot of sense.
3. In choosing `pydantic` I've tried to make sure that the schemas we write in this new  implementation are reusable. E.g. the `strawberry` library used by Tiziano in aiida-graphql [has built-in support for `pydantic`](https://strawberry.rocks/docs/integrations/pydantic), i.e. it should be possible to reuse the models we create here in case we ever want to go in this direction.

I'm closing this for now, feel free to reopen if you think this should be seriously considered at this stage.

**Comment by chrisjsewell** [comment]
No thats absolutely fine, thanks for the response. We should probably add a note on this also in the AEP.
Yes I noticed pydantic support, so that is nice.

I do think though that the `/querybuilder` should probably only be used as a "last resort", in lieu of there being a specific endpoint for the query. Or at the least we should look to enforce some form of pagination (i.e. so you can't inadvertently ask for the server to send you millions of rows of data)

**Comment by ltalirz** [comment]
@chrisjsewell I just received a question from @JPchico on why you chose graphene over strawberry for this project. Can you please briefly comment?

**Comment by chrisjsewell** [comment]
https://github.com/aiidateam/aiida-restapi/pull/17#discussion_r645211740

https://github.com/aiidateam/aiida-restapi/pull/17#issuecomment-854857704

**Comment by JPchico** [comment]
Thanks @chrisjsewell , I was seeing that [now](https://fastapi.tiangolo.com/advanced/graphql/#graphql-with-strawberry) Strawberry is the recommended, I guess that that is something that changed from when the initial implementation was done.
