### ISSUE TITLE
Missing package errors when starting the REST API service 

### ISSUE THREAD

**Issue by flavianojs** [aiidateam/aiida-restapi#32]
I installed the aiida-restapi package in a new python virtual environment. Then, I tried to start the REST API with `uvicorn aiida_restapi:app` command. I got the following error:

`ModuleNotFoundError: No module named 'jose'`

I installed manually this module with `pip install python-jose`.
The next error was:

 `ModuleNotFoundError: No module named 'passlib'`

which I solved with `pip install passlib`.

The final error was:

`RuntimeError: Form data requires "python-multipart" to be installed.`

solved with `pip install python-multipart`. Then finally it worked.

**Comment by ltalirz** [comment]
This happens when not installing the `auth` extra - currently, the `auth` extra is necessary to run the REST API.

In order to install the REST API in editable mode with the auth extra, use

```
pip install -e .[auth]
```

**Comment by flavianojs** [comment]
Thanks, @ltalirz !
