### ISSUE TITLE
Compatibility with aiida-core 2.5

### ISSUE THREAD

**Issue by qiaojunfeng** [aiidateam/aiida-restapi#70]
It seems like there are some dependency conflicts with recent version of `aiida-core`, e.g. `pydantic`

https://github.com/aiidateam/aiida-restapi/blob/e6dcaa0ba1252ff66d0476d1fdfed7d16a6a2c57/pyproject.toml#L31

for `aiida-core v2.5.1`
https://github.com/aiidateam/aiida-core/blob/v2.5.1/pyproject.toml#L42

Are there any plans to update this package? Thanks!

**Comment by ltalirz** [comment]
looks like @agoscinski last worked on it

**Comment by eimrek** [comment]
thanks for making this issue. yes, the plan is to make this the official aiida REST API and deprecate the one built into aiida-core. Making it compatible with latest aiida-core is very important. @agoscinski indeed has been contributing to this repo and this could be a valuable next addition, if he has time.

**Comment by agoscinski** [comment]
Haven't looked to it more than trying to run it. There were some pydantic errors when I updated that is why the pydantic version is pinned. Not sure yet how hard to solve this is. Will look into this more later.

**Comment by qiaojunfeng** [comment]
Thank you all for the replies!

> There were some pydantic errors when I updated that is why the pydantic version is pinned. Not sure yet how hard to solve this is. Will look into this more later.

Yes I tried the same, and to me it's not straightforward to solve the pydantic stuff.
Would be very useful if the restapi can be revived some time later.
